# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-cards',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/nbdev-cards',
                'lib_path': 'nbdev_cards'},
  'syms': { 'nbdev_cards.card': {'nbdev_cards.card.foo': ('card.html#foo', 'nbdev_cards/card.py')},
            'nbdev_cards.core': {'nbdev_cards.core.foo': ('deck.html#foo', 'nbdev_cards/core.py')}}}